### ISSUE TITLE
[BUG] Action tab headers appearing shifted by one column

### ISSUE THREAD

**Issue by john-martinez-729** [eastcw/foundryvtt-dnd5eCharacterActions#7]
**Describe the bug**

<img width="629" alt="Screenshot 2023-11-13 205539" src="https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/assets/52676492/f80d919e-245d-4374-84c9-6d5dcb38647c">

The category headers seem to be shifted by one column. Range appears over what should be Hit/DC, etc.

**Comment by eastcw** [comment]
I'm not seeing this behavior on my system. What character sheet are you using and what version of the character sheet and character actions module are you on? Do you have any other modules active?

**Comment by Freeburn113** [comment]
I have the same issue and wanted to look if I can fix it myself
but I have it with the Tidy5e sheet
https://github.com/sdenec/tidy5e-sheet

**Comment by eastcw** [comment]
Ah I see. Unfortunately since Tidy5e sheet overrules my CSS and uses its own, so there's nothing I can do to fix this from my end; it looks relatively easy to fix from their end. I don't think the release version of Tidy5e is under active development, so raising an issue there is probably a waste of time. The [new alpha version](https://github.com/kgar/foundry-vtt-tidy-5e-sheets) of Tidy5e doesn't seem to support this Character Actions list at all. It [looks like they're working](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/issues/1) to natively support a similar actions tab without requiring this module, and what's been implemented so far looks like it will fix this issue

**Comment by kgar** [comment]
Hello, Tidy 5e rewriter here. @eastcw is right: in the latest version of the alpha sheets, there is a native actions list available through the tab selection UI. I am unfortunately unable to bank the time to fix the original sheets' style issues because of the sheer volume of alpha/beta work I'm doing on the rewrite. In some months, the rewrite will become the official version in Foundry. If there are modules you'd like to see work with the new sheets, feel free to drop a github issue on the [rewrite repo](https://github.com/kgar/foundry-vtt-tidy-5e-sheets).

Disclaimer: I do not have ownership of the original sheets and have only submitted functional fixes for things like dnd5e 2.4.x. Also, the code base of the original is in a state which inspired a full from-scratch rewrite.
